on: [push]

jobs:
  armv7_job:
    runs-on: ubuntu-18.04
    name: Build on ARMv7 
    steps:
      - uses: actions/checkout@master
      - uses: chensheng0/run-on-arch-action@v1.0.5
        id: runcmd
        with:
          architecture: armv7
          distribution: ubuntu18.04
          run: |
            uname -a >test.txt
            ls
            go version
            go build -o testx .
            echo ::set-output name=uname::$(uname -a)
            echo ::set-output name=goversion::$(go version)
      - name: Get the output
        run: |
            echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
            echo "The goversion output was ${{ steps.runcmd.outputs.goversion }}"
      - name: Get the output
        run: |
            pwd
            ls
            cat test.txt
